# Commodity Aliases
# Maps common user input variants (lowercase) → list of canonical names from Data_mapping.py
# A single query can resolve to multiple commodities (e.g. "paddy" → common + basmati)

COMMODITY_ALIASES: dict[str, list[str]] = {

    # --- Paddy / Rice ---
    "paddy":                    ["Paddy(Common)", "Paddy(Basmati)"],
    "paddy rice":               ["Paddy(Common)", "Paddy(Basmati)"],
    "dhan":                     ["Paddy(Common)", "Paddy(Basmati)"],
    "paddy common":             ["Paddy(Common)"],
    "common paddy":             ["Paddy(Common)"],
    "paddy basmati":            ["Paddy(Basmati)"],
    "basmati paddy":            ["Paddy(Basmati)"],
    "rice":                     ["Rice", "Basmati Rice", "Beaten Rice", "Broken Rice"],
    "basmati":                  ["Basmati Rice", "Paddy(Basmati)"],
    "basmati rice":             ["Basmati Rice", "Paddy(Basmati)"],
    "broken rice":              ["Broken Rice"],
    "beaten rice":              ["Beaten Rice"],
    "poha":                     ["Beaten Rice"],
    "chura":                    ["Beaten Rice"],

    # --- Wheat ---
    "wheat":                    ["Wheat", "Wheat Atta"],
    "gehu":                     ["Wheat"],
    "atta":                     ["Wheat Atta"],
    "wheat flour":              ["Wheat Atta"],
    "maida":                    ["Maida Atta"],
    "maida atta":               ["Maida Atta"],

    # --- Maize / Corn ---
    "maize":                    ["Maize"],
    "corn":                     ["Maize", "Sweet Corn "],
    "makka":                    ["Maize"],
    "makki":                    ["Maize"],
    "sweet corn":               ["Sweet Corn "],

    # --- Sorghum / Millets ---
    "jowar":                    ["Jowar(Sorghum)"],
    "sorghum":                  ["Jowar(Sorghum)"],
    "bajra":                    ["Bajra(Pearl Millet/Cumbu)"],
    "pearl millet":             ["Bajra(Pearl Millet/Cumbu)"],
    "cumbu":                    ["Bajra(Pearl Millet/Cumbu)"],
    "ragi":                     ["Ragi(Finger Millet)"],
    "finger millet":            ["Ragi(Finger Millet)"],
    "nachni":                   ["Ragi(Finger Millet)"],
    "foxtail millet":           ["Foxtail Millet(Navane)"],
    "navane":                   ["Foxtail Millet(Navane)"],
    "kodo millet":              ["Kodo Millet(Varagu)"],
    "varagu":                   ["Kodo Millet(Varagu)"],
    "barnyard millet":          ["Barnyard Millet"],
    "browntop millet":          ["Browntop Millet"],
    "proso millet":             ["Proso Millet"],
    "little millet":            ["Little Millet "],

    # --- Pulses ---
    "arhar":                    ["Red gram/Arhar/Tur(whole)", "Red gram split/Arhar dal/Tur dal"],
    "tur":                      ["Red gram/Arhar/Tur(whole)", "Red gram split/Arhar dal/Tur dal"],
    "toor":                     ["Red gram/Arhar/Tur(whole)", "Red gram split/Arhar dal/Tur dal"],
    "red gram":                 ["Red gram/Arhar/Tur(whole)", "Red gram split/Arhar dal/Tur dal"],
    "pigeon pea":               ["Red gram/Arhar/Tur(whole)"],
    "arhar dal":                ["Red gram split/Arhar dal/Tur dal"],
    "tur dal":                  ["Red gram split/Arhar dal/Tur dal"],
    "toor dal":                 ["Red gram split/Arhar dal/Tur dal"],
    "moong":                    ["Green Gram(Moong)(Whole)", "Green Gram Dal(Moong Dal)"],
    "mung":                     ["Green Gram(Moong)(Whole)", "Green Gram Dal(Moong Dal)"],
    "green gram":               ["Green Gram(Moong)(Whole)", "Green Gram Dal(Moong Dal)"],
    "moong dal":                ["Green Gram Dal(Moong Dal)"],
    "mung dal":                 ["Green Gram Dal(Moong Dal)"],
    "urad":                     ["Black Gram(Urd Beans)(Whole)", "Black Gram Dal(Urd Dal)"],
    "urd":                      ["Black Gram(Urd Beans)(Whole)", "Black Gram Dal(Urd Dal)"],
    "black gram":               ["Black Gram(Urd Beans)(Whole)", "Black Gram Dal(Urd Dal)"],
    "urad dal":                 ["Black Gram Dal(Urd Dal)"],
    "urd dal":                  ["Black Gram Dal(Urd Dal)"],
    "chana":                    ["Bengal Gram(Gram)(Whole)", "Bengal Gram Dal(Chana Dal)"],
    "chickpea":                 ["Bengal Gram(Gram)(Whole)", "Kabuli Chana(Chickpeas-White)"],
    "gram":                     ["Bengal Gram(Gram)(Whole)", "Bengal Gram Dal(Chana Dal)"],
    "chana dal":                ["Bengal Gram Dal(Chana Dal)"],
    "kabuli chana":             ["Kabuli Chana(Chickpeas-White)"],
    "white chickpea":           ["Kabuli Chana(Chickpeas-White)"],
    "masur":                    ["Lentil(Masur)(Whole)", "Masur Dal"],
    "masoor":                   ["Lentil(Masur)(Whole)", "Masur Dal"],
    "lentil":                   ["Lentil(Masur)(Whole)", "Masur Dal"],
    "masur dal":                ["Masur Dal"],
    "masoor dal":               ["Masur Dal"],
    "cowpea":                   ["Cowpea(Lobia/Karamani)", "Cowpea(Veg)"],
    "lobia":                    ["Cowpea(Lobia/Karamani)"],
    "rajma":                    ["Kidney Beans(Rajma)"],
    "kidney beans":             ["Kidney Beans(Rajma)"],
    "moth":                     ["Moath Dal"],
    "moath":                    ["Moath Dal"],
    "horse gram":               ["Kulthi(Horse Gram)"],
    "kulthi":                   ["Kulthi(Horse Gram)"],
    "peas":                     ["Green Peas", "Peas Wet", "Peas(Dry)"],
    "green peas":               ["Green Peas", "Peas Wet"],
    "dry peas":                 ["Peas(Dry)"],

    # --- Vegetables ---
    "tomato":                   ["Tomato"],
    "tamatar":                  ["Tomato"],
    "onion":                    ["Onion", "Onion Green"],
    "pyaz":                     ["Onion", "Onion Green"],
    "green onion":              ["Onion Green"],
    "spring onion":             ["Onion Green"],
    "potato":                   ["Potato"],
    "aloo":                     ["Potato"],
    "brinjal":                  ["Brinjal"],
    "eggplant":                 ["Brinjal"],
    "baingan":                  ["Brinjal"],
    "bhindi":                   ["Bhindi(Ladies Finger)", "Ladies Finger"],
    "ladies finger":            ["Bhindi(Ladies Finger)", "Ladies Finger"],
    "okra":                     ["Bhindi(Ladies Finger)", "Ladies Finger"],
    "cauliflower":              ["Cauliflower"],
    "gobi":                     ["Cauliflower", "Cabbage"],
    "phool gobi":               ["Cauliflower"],
    "cabbage":                  ["Cabbage"],
    "patta gobi":               ["Cabbage"],
    "carrot":                   ["Carrot"],
    "gajar":                    ["Carrot"],
    "radish":                   ["Raddish"],
    "mooli":                    ["Raddish"],
    "spinach":                  ["Spinach"],
    "palak":                    ["Spinach"],
    "capsicum":                 ["Capsicum"],
    "shimla mirch":             ["Capsicum"],
    "bell pepper":              ["Capsicum"],
    "green chilli":             ["Green Chilli"],
    "hari mirch":               ["Green Chilli"],
    "chilli":                   ["Green Chilli", "Chili Red", "Dry Chillies"],
    "red chilli":               ["Chili Red", "Dry Chillies"],
    "mirch":                    ["Green Chilli", "Chili Red"],
    "dry chilli":               ["Dry Chillies"],
    "lal mirch":                ["Chili Red", "Dry Chillies"],
    "bitter gourd":             ["Bitter gourd"],
    "karela":                   ["Bitter gourd"],
    "bottle gourd":             ["Bottle gourd"],
    "lauki":                    ["Bottle gourd"],
    "pumpkin":                  ["Pumpkin"],
    "kaddu":                    ["Pumpkin", "Sweet Pumpkin"],
    "ash gourd":                ["Ashgourd"],
    "pethakaddu":               ["Ashgourd"],
    "drumstick":                ["Drumstick"],
    "murungakkai":              ["Drumstick"],
    "cluster beans":            ["Cluster beans"],
    "guar":                     ["Guar", "Cluster beans"],
    "garlic":                   ["Garlic"],
    "lahsun":                   ["Garlic"],
    "ginger":                   ["Ginger(Green)", "Ginger(Dry)"],
    "adrak":                    ["Ginger(Green)"],
    "sonth":                    ["Ginger(Dry)"],
    "dry ginger":               ["Ginger(Dry)"],
    "green ginger":             ["Ginger(Green)"],
    "coriander leaves":         ["Coriander(Leaves)"],
    "dhania leaves":            ["Coriander(Leaves)"],
    "methi":                    ["Methi(Leaves)", "Methi Seeds"],
    "fenugreek":                ["Methi(Leaves)", "Methi Seeds"],
    "fenugreek seeds":          ["Methi Seeds"],
    "methi seeds":              ["Methi Seeds"],
    "methi leaves":             ["Methi(Leaves)"],
    "sweet potato":             ["Sweet Potato"],
    "shakarkand":               ["Sweet Potato"],
    "taro":                     ["Colacasia"],
    "arvi":                     ["Colacasia"],

    # --- Fruits ---
    "mango":                    ["Mango", "Mango(Raw-Ripe)"],
    "aam":                      ["Mango", "Mango(Raw-Ripe)"],
    "raw mango":                ["Mango(Raw-Ripe)"],
    "banana":                   ["Banana", "Banana - Green"],
    "kela":                     ["Banana", "Banana - Green"],
    "green banana":             ["Banana - Green"],
    "apple":                    ["Apple"],
    "seb":                      ["Apple"],
    "grapes":                   ["Grapes"],
    "angoor":                   ["Grapes"],
    "orange":                   ["Orange"],
    "santra":                   ["Orange"],
    "mosambi":                  ["Mousambi(Sweet Lime)"],
    "sweet lime":               ["Mousambi(Sweet Lime)"],
    "mousambi":                 ["Mousambi(Sweet Lime)"],
    "papaya":                   ["Papaya", "Papaya(Raw)"],
    "pineapple":                ["Pineapple"],
    "pomegranate":              ["Pomegranate"],
    "anar":                     ["Pomegranate"],
    "guava":                    ["Guava"],
    "amrud":                    ["Guava"],
    "lemon":                    ["Lemon"],
    "nimbu":                    ["Lemon"],
    "lime":                     ["Lime"],
    "watermelon":               ["Water Melon"],
    "tarbooz":                  ["Water Melon"],
    "muskmelon":                ["Karbuja(Musk Melon)"],
    "kharbooja":                ["Karbuja(Musk Melon)"],
    "litchi":                   ["Litchi"],
    "kinnow":                   ["Kinnow"],
    "sapota":                   ["Chikoos(Sapota)"],
    "chikoo":                   ["Chikoos(Sapota)"],
    "jackfruit":                ["Jack Fruit(Ripe)", "Jackfruit(Green/Raw/Unripe)"],
    "custard apple":            ["Custard Apple(Sharifa)"],
    "sitafal":                  ["Custard Apple(Sharifa)"],
    "peach":                    ["Peach"],
    "plum":                     ["Plum"],
    "pear":                     ["Pear(Marasebu)"],
    "amla":                     ["Amla(Nelli Kai)"],
    "gooseberry":               ["Goose berry(Nellikkai)", "Amla(Nelli Kai)"],
    "strawberry":               ["Strawberry"],
    "dragon fruit":             ["Dragon fruit"],

    # --- Spices ---
    "turmeric":                 ["Turmeric", "Turmeric(raw)"],
    "haldi":                    ["Turmeric", "Turmeric(raw)"],
    "raw turmeric":             ["Turmeric(raw)"],
    "black pepper":             ["Black pepper"],
    "kali mirch":               ["Black pepper"],
    "pepper":                   ["Black pepper", "Pepper garbled", "Pepper ungarbled"],
    "cardamom":                 ["Cardamom", "Large Cardamom"],
    "elaichi":                  ["Cardamom"],
    "jeera":                    ["Cummin Seed(Jeera)"],
    "cumin":                    ["Cummin Seed(Jeera)"],
    "cummin":                   ["Cummin Seed(Jeera)"],
    "coriander seed":           ["Corriander seed"],
    "dhania":                   ["Corriander seed", "Coriander(Leaves)"],
    "cloves":                   ["Cloves"],
    "laung":                    ["Cloves"],
    "cinnamon":                 ["Cinamon(Dalchini)"],
    "dalchini":                 ["Cinamon(Dalchini)"],
    "nutmeg":                   ["Nutmeg"],
    "jaiphal":                  ["Nutmeg"],
    "mace":                     ["Mace"],
    "javitri":                  ["Mace"],
    "saffron":                  ["Saffron"],
    "kesar":                    ["Saffron"],
    "ajwain":                   ["Ajwan"],
    "fennel":                   ["Soanf"],
    "saunf":                    ["Soanf"],
    "coconut":                  ["Coconut", "Tender Coconut"],
    "nariyal":                  ["Coconut"],
    "tender coconut":           ["Tender Coconut"],
    "arecanut":                 ["Arecanut(Betelnut/Supari)", "Betelnuts"],
    "supari":                   ["Arecanut(Betelnut/Supari)"],
    "betelnut":                 ["Arecanut(Betelnut/Supari)"],

    # --- Oilseeds ---
    "groundnut":                ["Groundnut", "Groundnut(Split)", "Ground Nut Seed"],
    "peanut":                   ["Groundnut"],
    "mungfali":                 ["Groundnut"],
    "mustard":                  ["Mustard"],
    "sarson":                   ["Mustard"],
    "soybean":                  ["Soyabean"],
    "soyabean":                 ["Soyabean"],
    "sunflower":                ["Sunflower/Sunflower Seed"],
    "castor":                   ["Castor Seed"],
    "castor seed":              ["Castor Seed"],
    "linseed":                  ["Linseed"],
    "flaxseed":                 ["Linseed"],
    "alsi":                     ["Linseed"],
    "sesame":                   ["Sesamum(Sesame,Gingelly,Til)"],
    "til":                      ["Sesamum(Sesame,Gingelly,Til)"],
    "gingelly":                 ["Sesamum(Sesame,Gingelly,Til)"],
    "safflower":                ["Safflower"],
    "niger seed":               ["Niger Seed(Ramtil)"],
    "ramtil":                   ["Niger Seed(Ramtil)"],
    "copra":                    ["Copra"],
    "cotton seed":              ["Cotton Seed"],

    # --- Cash Crops ---
    "cotton":                   ["Cotton"],
    "sugarcane":                ["Sugarcane"],
    "ganna":                    ["Sugarcane"],
    "sugar":                    ["Sugar"],
    "jute":                     ["Jute"],
    "coffee":                   ["Coffee"],
    "tea":                      ["Tea"],
    "tobacco":                  ["Tobacco"],
    "rubber":                   ["Rubber"],

    # --- Misc Grains ---
    "barley":                   ["Barley(Jau)"],
    "jau":                      ["Barley(Jau)"],
    "oats":                     ["Barley(Jau)"],

    # --- Oils ---
    "groundnut oil":            ["Ground Nut Oil"],
    "mustard oil":              ["Mustard Oil"],
    "coconut oil":              ["Coconut Oil"],
    "gingelly oil":             ["Gingelly Oil"],
    "castor oil":               ["Castor Oil"],
    "ghee":                     ["Ghee"],
}
