from typing import Optional, List
from datetime import datetime
from uuid import UUID
from sqlalchemy.orm import Session

from app.models.alert import Alert
from app.models.user import User
from app.repositories.alert_repository import AlertRepository
from app.schemas.alert import (
    AlertSchema,
    AlertCommoditySchema,
    AlertMarketSchema,
    AlertPriceSchema,
    PaginatedAlertsResponse,
    AlertCreateSchema,
)

class AlertService:
    """Service layer for fetching user alerts and managing integration boundaries."""

    @staticmethod
    def _map_to_schema(alert: Alert) -> AlertSchema:
        price_schema: Optional[AlertPriceSchema] = None
        if alert.current_price is not None:
            price_schema = AlertPriceSchema(
                current=float(alert.current_price),
                previous=float(alert.previous_price) if alert.previous_price is not None else None,
                change_percent=float(alert.change_percent) if alert.change_percent is not None else None,
            )

        return AlertSchema(
            id=alert.id,
            type=alert.type,
            severity=alert.severity,
            title=alert.title,
            message=alert.message,
            commodity=AlertCommoditySchema(
                id=alert.commodity.id,
                name=alert.commodity.name,
            ),
            market=AlertMarketSchema(
                id=alert.market.id,
                name=alert.market.name,
            ),
            price=price_schema,
            created_at=alert.created_at,
        )

    @classmethod
    def get_alerts(
        cls,
        db: Session,
        user: User,
        type: Optional[str] = None,
        page: int = 1,
        page_size: int = 20,
    ) -> PaginatedAlertsResponse:
        items, total = AlertRepository.get_user_alerts(
            db=db,
            user_id=user.id,
            alert_type=type,
            page=page,
            page_size=page_size,
        )

        schema_items = [cls._map_to_schema(item) for item in items]
        return PaginatedAlertsResponse(
            items=schema_items,
            page=page,
            page_size=page_size,
            total=total,
        )

    @classmethod
    def get_alert_history(
        cls,
        db: Session,
        user: User,
        type: Optional[str] = None,
        search: Optional[str] = None,
        date_from: Optional[datetime] = None,
        date_to: Optional[datetime] = None,
        page: int = 1,
        page_size: int = 20,
    ) -> PaginatedAlertsResponse:
        items, total = AlertRepository.get_user_alert_history(
            db=db,
            user_id=user.id,
            alert_type=type,
            search=search,
            date_from=date_from,
            date_to=date_to,
            page=page,
            page_size=page_size,
        )

        schema_items = [cls._map_to_schema(item) for item in items]
        return PaginatedAlertsResponse(
            items=schema_items,
            page=page,
            page_size=page_size,
            total=total,
        )

    @staticmethod
    def create_alert(db: Session, alert_data: AlertCreateSchema) -> Alert:
        """Integration boundary helper to persist alerts generated by AI/ML business logic."""
        return AlertRepository.create_alert(db, alert_data)
